### ISSUE TITLE
Frequent crashes on Android 7.1

### ISSUE THREAD

**Issue by opk12** [abertschi/water-me#14]
I use version 1.0.5 from F-droid on Android 7.1 on a Samsung phone. I get the OS crash popup almost once a day.

```
FATAL EXCEPTION: main
Process: ch.abertschi.waterme.water_me, PID: 30723
android.app.RemoteServiceException: Bad notification posted from package ch.abertschi.waterme.water_me: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=ch.abertschi.waterme.water_me id=0x7f090000) visible user=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Comment by abertschi** [comment]
Please verify in #15
